{% set name = "trimesh" %}
{% set version = "4.5.2" %}
{% set sha256 = "165b12f2898c3e8dec99a2ed05ec5c83eafa2fc8150ba8c30f8b3a62f693433f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - numpy
  run_constrained:
    - jsonschema
    - mapbox_earcut
    - setuptools
    - scipy
    - pycollada
    - networkx
    - chardet
    - svg.path
    - xxhash
    - pillow
    - psutil
    - rtree
    - pyglet
    - sympy
    - meshio
    - msgpack-python
    - shapely
    - requests
    - lxml
    - colorlog
    - scikit-image

test:
  commands:
    - python -c "import trimesh"

about:
  home: https://github.com/mikedh/trimesh
  license: MIT

  # We can remove LICENSE.md from
  # the recipe when it is included
  # in the trimesh source dist:
  #
  # https://github.com/mikedh/trimesh/pull/176
  license_file: LICENSE.md
  summary: Import, export, process, analyze and view triangular meshes.
  dev_url: https://github.com/mikedh/trimesh

extra:
  recipe-maintainers:
    - mikedh
    - pauldmccarthy
