{% set name = "trimesh" %}
{% set version = "2.34.4" %}
{% set sha256 = "07c42e46cde1d1a5e19c5720d12c4997bb58e07d22b67461367bd8e2d138520a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - networkx
    - scipy
  run_constrained:
    - lxml
    - pyglet
    - Shapely
    - rtree
    - sympy
    - msgpack-python
    - colorlog
    - python-xxhash
    - pillow
    # these deps are not yet available on conda-forge
    # - python-fcl
    # - svg.path
    # - meshpy


test:
  commands:
    - python -c "import trimesh"


about:
  home: https://github.com/mikedh/trimesh
  license: MIT

  # We can remove LICENSE.md from
  # the recipe when it is included
  # in the trimesh source dist:
  #
  # https://github.com/mikedh/trimesh/pull/176
  license_file: LICENSE.md
  summary: 'Import, export, process, analyze and view triangular meshes.'
  dev_url: https://github.com/mikedh/trimesh

extra:
  recipe-maintainers:
    - mikedh
    - pauldmccarthy
