{% set name = "trimesh" %}
{% set version = "2.35.48" %}
{% set sha256 = "086c8ff0b443f581a2acc41f4fb33ccd6f230a6c9526fe91cbb7f772abbfbd2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - networkx
    - scipy
  run_constrained:
    - lxml
    - pyglet
    - Shapely
    - rtree
    - sympy
    - msgpack-python
    - colorlog
    - python-xxhash
    - pillow
    # these deps are not yet available on conda-forge
    # - python-fcl
    # - svg.path
    # - meshpy


test:
  commands:
    - python -c "import trimesh"


about:
  home: https://github.com/mikedh/trimesh
  license: MIT

  # We can remove LICENSE.md from
  # the recipe when it is included
  # in the trimesh source dist:
  #
  # https://github.com/mikedh/trimesh/pull/176
  license_file: LICENSE.md
  summary: 'Import, export, process, analyze and view triangular meshes.'
  dev_url: https://github.com/mikedh/trimesh

extra:
  recipe-maintainers:
    - mikedh
    - pauldmccarthy
